apiVersion: v1
kind: Service
metadata:
  name: muzahid-helloservice-backend-service
spec:
  selector:
    app: backend-helloservice
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
