replicaCount: 2

image:
  repository: muzahidulnisar/helloservice
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 3001

env:
  - name: NODE_ENV
    value: "production"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
